# Generated by Django 6.0.1 on 2026-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slugapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
